### PR TITLE
L2M0 Extras - Added MIDIKeyboard recipe for KeyListener practice

### PR DESCRIPTION
**Pull request by Zaelix**
Just a quick practice recipe that might be fun for students that have sound on their computer. It shows a simple KeyListener setup.

### CODE REVIEW

**Review by tylercwiltz — CHANGES_REQUESTED** [review]
Works perfectly!

There is a typo for instruction 15) change rowQP to rowZM.

Also I think either a comment in the recipe or something on the actual GUI that says to press the keys in order to hear the sounds(Students might be confused if it's only the blank frame that pops up)

**Comment by Zaelix** [comment]
> Works perfectly!
> 
> There is a typo for instruction 15) change rowQP to rowZM.
> 
> Also I think either a comment in the recipe or something on the actual GUI that says to press the keys in order to hear the sounds(Students might be confused if it's only the blank frame that pops up)

Good catch on that typo! As for the directions, step 8 already is explicitly telling them to run it and press a key on their keyboard to see if it plays a note.

**Comment by keithagroves** [comment]
I love the concept and the end result, but I think we should simplify it. Also, the notes are off because in music theory the note B is the same thing Cb.

I propose we strip out some of the extra stuff so the students build something like this:

```
package other;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.sound.midi.MidiChannel;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Synthesizer;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class MIDIKeyboard implements KeyListener {
	Synthesizer synth;
	public MidiChannel[] channels;
	JLabel noteLabel = new JLabel();
	int piano = 0;
	int drums = 9;

	static final int C = 60;
	static final int D = 62;
	static final int E = 64;
	static final int F = 65;
	static final int G = 67;
	static final int A = 69;
	static final int B = 71;

	String[] notes = { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "B#" };
	int lastKey = 0;

	public static void main(String[] args) {
		MIDIKeyboard keyboard = new MIDIKeyboard();
		keyboard.start();
	}

	private void start() {
		initialize();
		noteLabel.setFont(new Font("Arial", Font.BOLD, 40));
		noteLabel.setHorizontalAlignment(JLabel.CENTER);
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.addKeyListener(this);
		frame.setVisible(true);
		frame.add(noteLabel);
		frame.setPreferredSize(new Dimension(500, 500));
		frame.pack();
	}

	@Override
	public void keyPressed(KeyEvent e) {
		int keyCode = e.getKeyChar();
		lastKey = keyCode;
		if (keyCode == 'a') {
			playNote(C, piano);
		} else if (keyCode == 's') {
			playNote(D, piano);
		} else if (keyCode == 'd') {
			playNote(E, piano);
		} else if (keyCode == 'f') {
			playNote(F, piano);
		}
	}

	@Override
	public void keyReleased(KeyEvent e) {
		int keyCode = e.getKeyChar();
		if (keyCode == 'a') {
			stopNote(C, piano);
		} else if (keyCode == 's') {
			stopNote(D, piano);

		} else if (keyCode == 'd') {
			stopNote(E, piano);
		} else if (keyCode == 'f') {
			stopNote(F, piano);
		}
	}

	public void playNote(int note, int instrument) {
		noteLabel.setText(getNoteName(note));
		new Thread(new Runnable() {
			public void run() {
				channels[instrument].noteOn(note, 120);
			}
		}).start();
	}

	public void stopNote(int note, int instrument) {
		channels[instrument].noteOff(note);
	}

	private String getNoteName(int noteNumber) {
		String name = notes[((noteNumber - 5) % notes.length)];
		return name;
	}

	void initialize() {
		try {
			synth = MidiSystem.getSynthesizer();
			synth.open();
			channels = synth.getChannels();
		} catch (MidiUnavailableException e) {
			e.printStackTrace();
		}
	}

	public void playNote(int note, int octave, int instrument) {
		noteLabel.setText(getNoteName(note));
		new Thread(new Runnable() {
			public void run() {
				channels[instrument].noteOn(note + (12 * octave), 120);
			}
		}).start();
	}

	public void stopNote(int note, int octave, int instrument) {
		channels[instrument].noteOff(note + 12 * octave);
	}

	@Override
	public void keyTyped(KeyEvent e) {
	}
}
```

**Comment by Zaelix** [comment]
I've refactored to use more descriptive names, as well as fixing the (shameful) music theory mistake.

**Pull request merged**
