### PR TITLE
Feature/parse int

### PR DESCRIPTION
**Pull request by sebastianTroncoso93**
Finished checking details in parseInt repository, including changes in comments, grammar, and adding a line to check to see if the rider is less than 42 inches tall.

### CODE REVIEW

**Comment by sebastianTroncoso93** [comment]
Updated the rollercoaster.java file

**Comment by jaLeague** [comment]
Line 13 of StringsCannotAdd  siz -> six
Line 23, I think the use of asterisks is a bit confusing. It looks like the student is supposed to put them in the code?

**Comment by jaLeague** [comment]
I would like to put these new recipes into the L0restructure branch since it has a new hierarchy. We can then merge the new feature at the same time.

**Comment by sebastianTroncoso93** [comment]
I moved the file warmup roller coaster into the recipe roller coaster, and I removed some details from it as well.

**Comment by dencee** [comment]
Closing this PR because they were brought into the L0 restructure branch: https://github.com/League-central/java-modules/pull/143
which was committed into master in PR: https://github.com/League-central/java-modules/pull/147

**Pull request closed without merging**
