### PR TITLE
Update HighLowGame.java

### PR DESCRIPTION
**Pull request by KamiFightingSpirit**
The instructions were written in a non-intuitive way. I am not sure if there was a reason behind this but I took the liberty to rewrite them in a clear manner.

### CODE REVIEW

**Comment by mwoguri** [comment]
I like the text changes you made--things like "Tell the user they won" is an improvement over "Win" 😄 

With regards to the order, I think the idea is that after each step the student should be able to run their code and see the result of the step they did, so we'd want steps like "Repeat steps 1 to 10 ten times" to come near the end of the process so they have the chance to get their code running correctly while it's not in a loop--the program doing the wrong thing once is (hopefully) less confusing/frustrating than it doing the wrong thing 10 times.

**Comment by KamiFightingSpirit** [comment]
Your suggestion makes sense, but I would propose we don't Quentin Tarantino the instructions (don't start on number 3 and have the "Repeat steps 1-10 as number 11 while being above number 1 which is below 3 and 2). 
Instead have them be ordered, but get to the loop AFTER what was you have written and tell them to write.  This fulfills the goal of the loop not running 10 times the wrong way and allows them to test their code each step of the way, THEN add a loop.

**Comment by mwoguri** [comment]
There's a number of recipes throughout the levels that have steps that aren't followed from top to bottom.  It definitely confuses the students when first start doing recipes, though in my (very limited) experience they get used to it quickly.  Maybe @jaLeague or @DaveDLeague can comment?  I don't personally have any strong opinions on the matter.

**Comment by KamiFightingSpirit** [comment]
I just think this example was particularly confusing than the others I have come across and in Level 0 anything that can help a kid focus on "hey, we just called a method on a class without declaring a Random type first and that allowed us to directly instantiate an int variable" instead of getting distracted by something else where I'm not seeing a benefit. 
Will wait for others to chime in to hear the general thinking around this lesson structure.

**Comment by dencee** [comment]
Who is the owner of the highlow branch? https://github.com/League-central/java-modules/tree/highlow

**Comment by jaLeague** [comment]
I like the idea of the proposed change.  By this time, the student should know how to create a random number ( from module 2). So.....

In line with our new Level 0 standard for creating random numbers, please separate the creation of the Random object from the retrieval of the random integer and put in something like this:

Random ran = new Random();
int randomNumber; 
// Using the Random object, ran, initialize the randomNumber variable to a number between 1 and 100.

**Comment by KamiFightingSpirit** [comment]
I made the proposed changes. @jaLeague wanted to confirm you are aware that I was talking about the order of the instructions which were pretty jumbled up on this one.

**Comment by DaveDLeague** [comment]
It is a weird balance trying to decide what order the steps should go. I like the changes that were made and in this case, they improve the recipe. If I had to add something, I would add a note on step 2 that explains that this is for programmer testing. I almost always get students telling me that this will spoil the game for the player.

**Pull request merged**
