### PR TITLE
L3 rework

### PR DESCRIPTION
**Pull request by dencee**
THIS COMMIT MUST BE IN SYNC WITH THE L3 REWORK JAVA-CURRICULUM COMMIT

### CODE REVIEW

**Comment by jaLeague** [comment]
Some feedback on first 2 modules. 

Module 0,  class _00_ArrayDemo. Line 25 says ArrayList   - should be array.

Module 1, class _02_GuestBook.  Since there is a recipe web page, it would be useful to add a link to it in the package (see level 0). Same for class  _02_LogSearch in the HashMap section.

Module 1, class GameBoard in _01_Memory_Match. Line 49 says create objects with values 1,1   but the constructor only requires one int. 

Module 1, class California_Weather. Task 1 says to "Create a program to search for the weather of a city" but if I run the base code, this seems to have already been written so it's not really a task? 
Utilities class (line 28) says use the method to get a HashMap of a San Diego city. Should this be California city?

Module 1, _05_World_Clocks. Maybe add some help for the student to explain the expectation of how to use HashMaps for this solution (since it is a HashMap recipe).

Module 1 general comment. The recipes often embed the main method, program code, and unit tests in a single file. I think the tests should always be separated from the code being tested (e.g. _04_RemovingStuffFromArrayLists) but I also like consistency for a Runner class to be separated out.

**Comment by jaLeague** [comment]
Module 2 feedback. 
_00_Sorting_Demo. Line 120 typo. "based of the LAST letter" should read "based on the LAST letter". Maybe include a header about this being a CUSTOM sort and a little more about the compare method parameters / Comparator interface and its relationship to the Collections.sort method? Is it worth separating the sorting array demo from sorting ArrayList demo to emphasize difference?
_01_SortedArrayCheckerTest passes when no code is written. I have some students who would move on if the tests pass :) Perhaps uncomment the int array tests so it indicates work has to be done?
_02_SwappingDigits. Tests and code in same class. Inconsistent with SortedArrayCheckerTest and not best coding practice. Separate tests so student can test one at a time?
_03_VisualArraySorterSolution.pde  will not open in Processing (Invalid name). Can we present the instructions in a .pde instead of a .txt so the student will save code back into project for pushing to github (see level 0)?
_00_SortingAlgorithms. java has a failed import _02_Thanos_Sort.ThanosSort;
Since Heap, Insertion, Merge, Quick, and Selection sorts are no longer coding activities, i suggest they are removed from the "Activities " column of the module web page.
_03_SearchTest contains tests for InterpolationSearch and ExponentialSearch which are not activities to be coded?  Also SearchTest passes with no code written (see above).
_00_MoreAndMoreTests encourage code and tests to exist in the same class. Suggest separate classes (like Algorithms).

**Comment by jaLeague** [comment]
Module 3 feedback. 
_00_StringMethodsDemo. Line 42. typo. whitespace
_01_StringMethods. Not important, but I would add toUppercase() and String.valueOf() to list of useful String methods.
_02_StringBuilderDemo. line 6. typo.  "from a list"
line 12. typo. "to make the new one"
line 17. typo.    an "s"   or  "s"
_01_The_Wave.   The Background paragraph is a lot of text to scroll past, particularly on a small low res screen. I suggest just including the link for students who do not know what an audience "wave" is.

**Comment by jaLeague** [comment]
Module 4 feedback.
_00_StackDemo. I suggest including a warning that popping from an empty stack incurs an error. Also emphasize that pop returns a value. Maybe an example of setting a variable from the pop. I get a lot of students that don't get either of these ideas currently.
_03_TestMatchingBrackets. Test and code in same class.
_00_QueueDemo.  Explanation just talks about Queue, but code uses ArrayDeque with no explanation of the relationship. This is a different pattern from Stack (the previous demo) so should be explained? 
_01_IntroToQueue. line 46.  emit??  change to issue?   Also tests and code in same class.
_02_Hangman.  Instructions say to run the jar. I am not able to run the jar (I think it is looking in the wrong place for the dictionary  "src/_04_HangMan" ?
_03_MazeMaker. Instructions could use some reformatting. The instructions also say to remove to random outside walls to make an entrance and exit to the maze, but I could not find that instruction in the code.

**Comment by jaLeague** [comment]
Module 5 feedback.
_00_IntroToRecursion. lines 6 and 11. typo  "itself"
_01_Factorial. line 6. Should this be between n and 1 ?
_02_StringTrimmer. Test and code in same class.
_03_RecursionMath. lines 20 and 21. spelling. numberToDivideBy
There are tests in _03_RecursionMath and a separate _03_RecursionMathTest class ?

**Comment by dencee** [comment]
@jaLeague Fixed all reported issues. Thanks for the review 👍

**Pull request merged**
