### PR TITLE
L1feature/solar system

### PR DESCRIPTION
**Pull request by dencee**

### CODE REVIEW

**Comment by tylercwiltz** [comment]
I think this is really cool! I like the counter for the number of days. A few changes I would make are:

1) the distance from sun refers to the orbitWidth variable so maybe change the name to make it a little more intuitive. The orbitWidth variable for the earth is set to 200, but earth's distance on the chart is 149,600,000, so maybe changing orbitWidth to 149 or 150 would help with the confusion? 

2) the sun is too large so Mercury and Venus are inside the sun when drawn 

3) I just ended up calling addMoon() in the SolarSystem constructor, but maybe give the students a little more guidance in the instructions with that? Unless you want them to completely figure it out on their own because it's extra.

**Review by tylercwiltz — COMMENTED** [review]
I think this is really cool! I like the counter for the number of days. A few changes I would make are:

the distance from sun refers to the orbitWidth variable so maybe change the name to make it a little more intuitive. The orbitWidth variable for the earth is set to 200, but earth's distance on the chart is 149,600,000, so maybe changing orbitWidth to 149 or 150 would help with the confusion?

the sun is too large so Mercury and Venus are inside the sun when drawn

I just ended up calling addMoon() in the SolarSystem constructor, but maybe give the students a little more guidance in the instructions with that? Unless you want them to completely figure it out on their own because it's extra.

**Comment by dencee** [comment]
@tylercwiltz Added changes. Thanks for the feedback!

**Review by tylercwiltz — APPROVED** [review]
Looks all good to me now!

**Pull request merged**
