### PR TITLE
L3M1: New Retro Sun recipe

### PR DESCRIPTION
**Pull request by dencee**

### CODE REVIEW

**Review by tylercwiltz — CHANGES_REQUESTED** [review]
I get a 404 when trying to open the instructions, so I didn't go through the recipe yet. I did check for spelling errors in the comments, and didn't see any.  Also I believe this should be in L3M0, but ended up in L3M1 and packages 6 - 9 need to have the packages renamed to the correct number inside the file.

**Comment by dencee** [comment]
@tylercwiltz The 404 error goes away when the curriculum PR is committed. The instructions are a redirect to keep both instructions in sync.
The code can be done using either lists (M1) or arrays (M0) and chose to use lists because those recipes are currently not that exciting or filled out.
Good catch on the file package numbers 👍

**Comment by tylercwiltz** [comment]
@dencee Definitely a cool recipe and should be a lot of fun for the students, however I think it may be a little challenging for them? A few suggestions that could make it easier for students: 

1) Move the closing curly brace of draw to after step 6. Currently it's after step 2, which could be confusing for students. 
2) Maybe include a link to the loadPixels() and pixels[] processing documentation so students are familiar with how to use it. 
3) In part 3 where you talk about making the (x,y,width,height) variables, maybe mention that they should be floats(you do, but not until the later steps.
4) Include more detailed instructions for part 5. Parts 1-4 are fairly detailed so students might be confused on how to implement part 5 with the few instructions given.

These are just my thoughts addressing the difficulty, other than that I think it's great!

**Comment by dencee** [comment]
@tylercwiltz Suggestions 1-3 committed, thanks 👍
I'm going to contest you on part 4 and the difficulty. As the last recipe on ArrayLists I think it's ok for it to be a bit ambiguous on the last instructions where they would actually have to do some thinking on their own. I think it's no more difficult than the last recipe for 2D arrays, wrong way cow. Only way to know for sure if it's too hard is to test it out. I'd rather it be too hard and we make it easier than the other way around.

**Review by tylercwiltz — APPROVED** [review]

**Pull request merged**
